// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvwv3mdIRgzW6ERUbOQSjcj_UpfKIyjNA',
    appId: '1:799531082625:android:0191dba4697afbd6583e80',
    messagingSenderId: '799531082625',
    projectId: 'mobile-samawa',
    storageBucket: 'mobile-samawa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq66u4E4ypJewpIqK_aej3EXW-aAKSjcQ',
    appId: '1:799531082625:ios:536f570cc69d683e583e80',
    messagingSenderId: '799531082625',
    projectId: 'mobile-samawa',
    storageBucket: 'mobile-samawa.appspot.com',
    androidClientId: '799531082625-9oprnhismbh9rckjc1hoo5g1eo1eeoe7.apps.googleusercontent.com',
    iosClientId: '799531082625-iun6ddg9cr0ubo5lj7cnh7jjhaq2s7eh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileSamawa',
  );
}
